// test_inbox_resolution.js - Automated tests for inbox resolution
const assert = require('assert');
const fs = require('fs');
const path = require('path');
const express = require('express');
const { createClient } = require('@supabase/supabase-js');

const inbox = require('./inbox');
const bokun = require('./bokun');

let passedTests = 0;
function test(name, fn) {
  try {
    fn();
    console.log(`✓ ${name}`);
    passedTests++;
  } catch (err) {
    console.error(`✗ ${name}`);
    console.error(err);
    process.exit(1);
  }
}

async function asyncTest(name, fn) {
  try {
    await fn();
    console.log(`✓ ${name}`);
    passedTests++;
  } catch (err) {
    console.error(`✗ ${name}`);
    console.error(err);
    process.exit(1);
  }
}

async function runAllTests() {
  console.log('--- Running Inbox Resolution Test Suite ---\n');

  // Test 1: Phone normalization variants
  test('R1: getPhoneVariants produces clean digits and standard formats', () => {
    const v1 = inbox.getPhoneVariants('+61400040043');
    assert(v1.includes('61400040043'), 'Must include plain digits');
    assert(v1.includes('+61400040043'), 'Must include + leading format');
    assert(v1.includes('0400040043'), 'Must include AU local format');

    const v2 = inbox.getPhoneVariants('61400040043');
    assert(v2.includes('61400040043'));
    assert(v2.includes('+61400040043'));

    const v3 = inbox.getPhoneVariants('+61 400 040 043');
    assert(v3.includes('61400040043'));
    assert(v3.includes('+61400040043'));

    const v4 = inbox.getPhoneVariants(' 61400040043 ');
    assert(v4.includes('61400040043'));

    // URL encoded %2B and double encoded %252B
    const v5 = inbox.getPhoneVariants('%2B61400040043');
    assert(v5.includes('61400040043'), 'Must decode %2B without leaving digit 2');
    assert(v5.includes('+61400040043'));

    const v6 = inbox.getPhoneVariants('%252B61400040043');
    assert(v6.includes('61400040043'), 'Must handle double-encoded %252B');

    // Edge cases: null, undefined, empty
    assert.deepStrictEqual(inbox.getPhoneVariants(''), []);
    assert.deepStrictEqual(inbox.getPhoneVariants(null), []);
    assert.deepStrictEqual(inbox.getPhoneVariants(undefined), []);
  });

  // Test 2: PostgREST filter encoding eliminates raw plus signs
  test('R1: toPostgrestInList quotes values containing special characters to prevent PostgREST syntax errors', () => {
    const rawVariants = ['61400040043', '+61400040043', '0400040043'];
    const postgrestList = inbox.toPostgrestInList(rawVariants);
    
    assert.strictEqual(postgrestList[0], '61400040043', 'Plain digits stay unquoted');
    assert.strictEqual(postgrestList[1], '"+61400040043"', 'Variants with + MUST be enclosed in double quotes');
    assert.strictEqual(postgrestList[2], '0400040043', 'Local digits stay unquoted');

    // Verify PostgREST URL generated by supabase-js
    const dummyClient = createClient('https://mock.supabase.co', 'mock-key');
    const query = dummyClient.from('messages').select('dir,body').in('phone', postgrestList);
    const searchString = query['url'].search;

    assert(!searchString.includes('phone=in.(+'), 'PostgREST query string MUST NOT contain raw unquoted plus sign');
    assert(searchString.includes('%22%2B61400040043%22'), 'Plus sign variant must be double-quoted and URL encoded');
  });

  // Test 3: Record and retrieve messages in fallback mode across all phone representations
  await asyncTest('R1: Message retrieval and window status across phone variants', async () => {
    const testPhone = '61499988877';
    await inbox.record(testPhone, 'Alice Test', 'inbound', 'Hello from Alice', 'msg_001');
    await inbox.record(testPhone, 'Alice Test', 'outbound', 'Hi Alice! How can we help?', 'msg_002');

    // Fetch using different representations
    const msgs1 = await inbox.getMessages('61499988877');
    assert.strictEqual(msgs1.length, 2, 'Should find messages by plain digits');

    const msgs2 = await inbox.getMessages('+61499988877');
    assert.strictEqual(msgs2.length, 2, 'Should find messages by + prefix');

    const msgs3 = await inbox.getMessages('%2B61499988877');
    assert.strictEqual(msgs3.length, 2, 'Should find messages by %2B encoded string');

    const msgs4 = await inbox.getMessages(' 61499988877 ');
    assert.strictEqual(msgs4.length, 2, 'Should find messages with spaces');

    // 24h window test
    const isOpen = await inbox.isWindowOpen('+61499988877');
    assert.strictEqual(isOpen, true, 'Window should be open when recent inbound message exists');

    const isOpenEncoded = await inbox.isWindowOpen('%2B61499988877');
    assert.strictEqual(isOpenEncoded, true, 'Window check should work with URL-encoded phone');
  });

  // Test 4: Bokun booking retrieval across phone representations
  await asyncTest('R1: Bokun booking retrieval handles phone normalization', async () => {
    const bookingPayload = {
      bookingId: 'BK-TEST-001',
      customer: {
        firstName: 'Bob',
        lastName: 'Traveler',
        phoneNumber: '+61 411 222 333',
        email: 'bob@example.com'
      },
      activity: {
        title: 'Sunset Blue Mountains Tour',
        startDate: '2026-09-20',
        totalParticipants: 2
      },
      totalPrice: 280,
      currency: 'AUD',
      status: 'confirmed'
    };

    await bokun.recordBooking(bookingPayload);

    const b1 = await bokun.getBookingsForPhone('61411222333');
    assert(b1.length >= 1, 'Should find booking by plain digits');
    assert.strictEqual(b1[0].bookingId, 'BK-TEST-001');

    const b2 = await bokun.getBookingsForPhone('+61411222333');
    assert(b2.length >= 1, 'Should find booking by + prefix');

    const b3 = await bokun.getBookingsForPhone('%2B61411222333');
    assert(b3.length >= 1, 'Should find booking by %2B encoded string');
  });

  // Test 5: Endpoints in express app handle parameters safely
  await asyncTest('R1 & R2: Express API routes handle :phone properly', async () => {
    const app = express();
    app.get('/inbox/api/conversations/:phone/messages', async (req, res) => {
      try {
        const phone = String(req.params.phone || '').trim().replace(/^ /, '+');
        res.json(await inbox.getMessages(phone));
      } catch (e) {
        res.status(500).json({ error: e.message });
      }
    });

    app.get('/inbox/api/conversations/:phone/window', async (req, res) => {
      try {
        const phone = String(req.params.phone || '').trim().replace(/^ /, '+');
        res.json({ open: await inbox.isWindowOpen(phone) });
      } catch (e) {
        res.status(500).json({ error: e.message });
      }
    });

    const server = app.listen(0);
    const port = server.address().port;
    const axios = require('axios');

    try {
      const resMsg = await axios.get(`http://127.0.0.1:${port}/inbox/api/conversations/%2B61499988877/messages`);
      assert.strictEqual(resMsg.status, 200);
      assert(Array.isArray(resMsg.data));
      assert.strictEqual(resMsg.data.length, 2);

      const resWin = await axios.get(`http://127.0.0.1:${port}/inbox/api/conversations/%2B61499988877/window`);
      assert.strictEqual(resWin.status, 200);
      assert.strictEqual(resWin.data.open, true);
    } finally {
      server.close();
    }
  });

  // Test 6: Frontend inbox.html static validation
  test('R2 & R3: inbox.html contains required URL encoding, Call UX and status badges', () => {
    const html = fs.readFileSync(path.join(__dirname, 'inbox.html'), 'utf8');

    // Check fetch calls using encodeURIComponent(cur)
    assert(html.includes('/inbox/api/conversations/\'+encodeURIComponent(cur)+\'/messages'), 'Messages fetch must use encodeURIComponent(cur)');
    assert(html.includes('/inbox/api/conversations/\'+encodeURIComponent(cur)+\'/window'), 'Window fetch must use encodeURIComponent(cur)');
    assert(html.includes('/inbox/api/conversations/\'+encodeURIComponent(cur)+\'/bokun-bookings'), 'Bokun bookings fetch must use encodeURIComponent(cur)');
    assert(html.includes('/inbox/api/conversations/\'+encodeURIComponent(cur)+\'/reply'), 'Reply fetch must use encodeURIComponent(cur)');
    assert(html.includes('/inbox/api/conversations/\'+encodeURIComponent(cur)+\'/mark-handled'), 'Mark handled fetch must use encodeURIComponent(cur)');

    // Check Call UX
    assert(html.includes('id="chCallBtn"'), 'Must have chat header call button #chCallBtn');
    assert(html.includes('id="ciCallBtn"'), 'Must have contact info call button #ciCallBtn');
    assert(html.includes("'tel:'"), 'Must trigger phone dialer via tel:');
    assert(html.includes('btn-active-feedback'), 'Must provide visual active feedback for call button');

    // Check 24h window badge
    assert(html.includes("● Open (24h)"), 'Must display ● Open (24h)');
    assert(html.includes("● Closed"), 'Must display ● Closed');
    assert(html.includes('id="chStatus"'), 'Must have status badge #chStatus');
    assert(html.includes('id="chHumanTag"'), 'Must have human tag #chHumanTag');
  });

  console.log(`\nAll ${passedTests} tests passed successfully!`);
}

runAllTests().catch(err => {
  console.error('Test execution failed:', err);
  process.exit(1);
});
